name: bitsgap_tt
description: "A technical task for Bitsgap company"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.11

  mobx: ^2.4.0
  mobx_codegen: ^2.6.2
  flutter_mobx: ^2.2.1+1
  dio: ^5.7.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.3.2
  either_dart: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/png/
    - assets/svg/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/lato/Lato-Black.ttf
        - asset: assets/fonts/lato/Lato-BlackItalic.ttf
        - asset: assets/fonts/lato/Lato-Bold.ttf
        - asset: assets/fonts/lato/Lato-BoldItalic.ttf
        - asset: assets/fonts/lato/Lato-Italic.ttf
        - asset: assets/fonts/lato/Lato-Light.ttf
        - asset: assets/fonts/lato/Lato-LightItalic.ttf
        - asset: assets/fonts/lato/Lato-Regular.ttf
        - asset: assets/fonts/lato/Lato-Thin.ttf
        - asset: assets/fonts/lato/Lato-ThinItalic.ttf